// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/phoneyzm/phoneyzm.proto

package mu_micro_book_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PhoneYzm struct {
	Phone                int64    `protobuf:"varint,1,opt,name=Phone,proto3" json:"Phone,omitempty"`
	Yzm                  int64    `protobuf:"varint,2,opt,name=Yzm,proto3" json:"Yzm,omitempty"`
	IsUse                int64    `protobuf:"varint,3,opt,name=IsUse,proto3" json:"IsUse,omitempty"`
	ExTime               int64    `protobuf:"varint,4,opt,name=ExTime,proto3" json:"ExTime,omitempty"`
	CreateTime           int64    `protobuf:"varint,5,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	MechanismId          int64    `protobuf:"varint,6,opt,name=MechanismId,proto3" json:"MechanismId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PhoneYzm) Reset()         { *m = PhoneYzm{} }
func (m *PhoneYzm) String() string { return proto.CompactTextString(m) }
func (*PhoneYzm) ProtoMessage()    {}
func (*PhoneYzm) Descriptor() ([]byte, []int) {
	return fileDescriptor_567169c72ff799df, []int{0}
}

func (m *PhoneYzm) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneYzm.Unmarshal(m, b)
}
func (m *PhoneYzm) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneYzm.Marshal(b, m, deterministic)
}
func (m *PhoneYzm) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneYzm.Merge(m, src)
}
func (m *PhoneYzm) XXX_Size() int {
	return xxx_messageInfo_PhoneYzm.Size(m)
}
func (m *PhoneYzm) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneYzm.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneYzm proto.InternalMessageInfo

func (m *PhoneYzm) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *PhoneYzm) GetYzm() int64 {
	if m != nil {
		return m.Yzm
	}
	return 0
}

func (m *PhoneYzm) GetIsUse() int64 {
	if m != nil {
		return m.IsUse
	}
	return 0
}

func (m *PhoneYzm) GetExTime() int64 {
	if m != nil {
		return m.ExTime
	}
	return 0
}

func (m *PhoneYzm) GetCreateTime() int64 {
	if m != nil {
		return m.CreateTime
	}
	return 0
}

func (m *PhoneYzm) GetMechanismId() int64 {
	if m != nil {
		return m.MechanismId
	}
	return 0
}

type Error struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Datail               string   `protobuf:"bytes,2,opt,name=datail,proto3" json:"datail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_567169c72ff799df, []int{1}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDatail() string {
	if m != nil {
		return m.Datail
	}
	return ""
}

type Request struct {
	Phone                int64    `protobuf:"varint,1,opt,name=phone,proto3" json:"phone,omitempty"`
	MechanismId          int64    `protobuf:"varint,2,opt,name=MechanismId,proto3" json:"MechanismId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_567169c72ff799df, []int{2}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetPhone() int64 {
	if m != nil {
		return m.Phone
	}
	return 0
}

func (m *Request) GetMechanismId() int64 {
	if m != nil {
		return m.MechanismId
	}
	return 0
}

type Response struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error                *Error   `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Yzm                  int64    `protobuf:"varint,3,opt,name=yzm,proto3" json:"yzm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_567169c72ff799df, []int{3}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *Response) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func (m *Response) GetYzm() int64 {
	if m != nil {
		return m.Yzm
	}
	return 0
}

func init() {
	proto.RegisterType((*PhoneYzm)(nil), "mu.micro.book.srv.user.PhoneYzm")
	proto.RegisterType((*Error)(nil), "mu.micro.book.srv.user.Error")
	proto.RegisterType((*Request)(nil), "mu.micro.book.srv.user.Request")
	proto.RegisterType((*Response)(nil), "mu.micro.book.srv.user.Response")
}

func init() { proto.RegisterFile("proto/phoneyzm/phoneyzm.proto", fileDescriptor_567169c72ff799df) }

var fileDescriptor_567169c72ff799df = []byte{
	// 319 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x52, 0x41, 0x4b, 0xf3, 0x40,
	0x10, 0xa5, 0x4d, 0xd3, 0xf6, 0x9b, 0xc2, 0x87, 0x2c, 0x52, 0x16, 0xa1, 0x5a, 0x7a, 0xf2, 0xb4,
	0x42, 0xfb, 0x0b, 0x44, 0x8a, 0xf4, 0x20, 0x94, 0x55, 0x0f, 0x3d, 0xa6, 0xe9, 0x40, 0x43, 0xdd,
	0x6c, 0xdc, 0x4d, 0xc4, 0xe4, 0xe7, 0xf8, 0x0f, 0xfc, 0x87, 0xb2, 0x93, 0x4d, 0x09, 0x6a, 0x6f,
	0xde, 0xe6, 0xbd, 0x7d, 0xcc, 0xbc, 0x79, 0xb3, 0x30, 0xc9, 0x8c, 0xce, 0xf5, 0x4d, 0xb6, 0xd7,
	0x29, 0x96, 0x95, 0x3a, 0x16, 0x82, 0x78, 0x36, 0x56, 0x85, 0x50, 0x49, 0x6c, 0xb4, 0xd8, 0x6a,
	0x7d, 0x10, 0xd6, 0xbc, 0x89, 0xc2, 0xa2, 0x99, 0x7d, 0x74, 0x60, 0xb8, 0x76, 0xd2, 0x4d, 0xa5,
	0xd8, 0x39, 0x84, 0x54, 0xf3, 0xce, 0xb4, 0x73, 0x1d, 0xc8, 0x1a, 0xb0, 0x33, 0x08, 0x36, 0x95,
	0xe2, 0x5d, 0xe2, 0x02, 0xaf, 0x5b, 0xd9, 0x67, 0x8b, 0x3c, 0xa8, 0x75, 0x04, 0xd8, 0x18, 0xfa,
	0xcb, 0xf7, 0xa7, 0x44, 0x21, 0xef, 0x11, 0xed, 0x11, 0xbb, 0x04, 0xb8, 0x33, 0x18, 0xe5, 0x48,
	0x6f, 0x21, 0xbd, 0xb5, 0x18, 0x36, 0x85, 0xd1, 0x03, 0xc6, 0xfb, 0x28, 0x4d, 0xac, 0x5a, 0xed,
	0x78, 0x9f, 0x04, 0x6d, 0x6a, 0xb6, 0x80, 0x70, 0x69, 0x8c, 0x36, 0x8c, 0x41, 0x2f, 0xd6, 0xbb,
	0xc6, 0x1f, 0xd5, 0x6e, 0xec, 0x2e, 0xca, 0xa3, 0xe4, 0x85, 0x1c, 0xfe, 0x93, 0x1e, 0xcd, 0x6e,
	0x61, 0x20, 0xf1, 0xb5, 0x40, 0x9b, 0x3b, 0xbf, 0x59, 0x7b, 0x2f, 0x02, 0xdf, 0xe7, 0x76, 0x7f,
	0xce, 0x3d, 0xc0, 0x50, 0xa2, 0xcd, 0x74, 0x6a, 0x91, 0x71, 0x18, 0xd8, 0x22, 0x8e, 0xd1, 0x5a,
	0xea, 0x32, 0x94, 0x0d, 0x64, 0x0b, 0x08, 0xd1, 0xb9, 0xa3, 0x0e, 0xa3, 0xf9, 0x44, 0xfc, 0x1e,
	0xb5, 0xa0, 0x15, 0x64, 0xad, 0x75, 0xa1, 0x96, 0x95, 0xf2, 0x01, 0xba, 0x72, 0xfe, 0xd9, 0x5c,
	0xa2, 0xac, 0x14, 0x5b, 0xc3, 0xe8, 0x1e, 0xf3, 0xe3, 0x61, 0xae, 0x4e, 0xf5, 0xf4, 0x1b, 0x5e,
	0x4c, 0x4f, 0x0b, 0xbc, 0xff, 0x47, 0xf8, 0x5f, 0x67, 0xfe, 0x87, 0x4d, 0xb7, 0x7d, 0xfa, 0x5c,
	0x8b, 0xaf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x78, 0x8d, 0x76, 0x4b, 0x7d, 0x02, 0x00, 0x00,
}
