// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: proto/phoneyzm/phoneyzm.proto

package mu_micro_book_srv_user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Phoneyzm service

type PhoneyzmService interface {
	GetPhoneYzm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
	CreatePhoneYzm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error)
}

type phoneyzmService struct {
	c    client.Client
	name string
}

func NewPhoneyzmService(name string, c client.Client) PhoneyzmService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "mu.micro.book.srv.user"
	}
	return &phoneyzmService{
		c:    c,
		name: name,
	}
}

func (c *phoneyzmService) GetPhoneYzm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Phoneyzm.GetPhoneYzm", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *phoneyzmService) CreatePhoneYzm(ctx context.Context, in *Request, opts ...client.CallOption) (*Response, error) {
	req := c.c.NewRequest(c.name, "Phoneyzm.CreatePhoneYzm", in)
	out := new(Response)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Phoneyzm service

type PhoneyzmHandler interface {
	GetPhoneYzm(context.Context, *Request, *Response) error
	CreatePhoneYzm(context.Context, *Request, *Response) error
}

func RegisterPhoneyzmHandler(s server.Server, hdlr PhoneyzmHandler, opts ...server.HandlerOption) error {
	type phoneyzm interface {
		GetPhoneYzm(ctx context.Context, in *Request, out *Response) error
		CreatePhoneYzm(ctx context.Context, in *Request, out *Response) error
	}
	type Phoneyzm struct {
		phoneyzm
	}
	h := &phoneyzmHandler{hdlr}
	return s.Handle(s.NewHandler(&Phoneyzm{h}, opts...))
}

type phoneyzmHandler struct {
	PhoneyzmHandler
}

func (h *phoneyzmHandler) GetPhoneYzm(ctx context.Context, in *Request, out *Response) error {
	return h.PhoneyzmHandler.GetPhoneYzm(ctx, in, out)
}

func (h *phoneyzmHandler) CreatePhoneYzm(ctx context.Context, in *Request, out *Response) error {
	return h.PhoneyzmHandler.CreatePhoneYzm(ctx, in, out)
}
